name: File a Bug Issue
description: File a bug report
title: "[Bug]: <title and short description>"
labels: ["bug"]
projects: ["PlaceholderGames/21"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the bug report and enter what bug you have encountered, how you encountered it and what requirements must be met to have this bug issue close
  - type: textarea
    id: Bug-issue
    attributes:
      label: What is the bug that you found?
      description: Also mention how you encountered it and what problems it is causing for gameplay and include any photos or videos to help show the issue 
      placeholder: Tell us the bug you encountered!
    validations:
      required: true
